language: cpp

branches:
  only: 
    - master

addons:
  apt:
    packages:
      - g++-4.8
      - clang++-3.7
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7

compiler: g++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - git clone https://github.com/google/googletest.git
  - mkdir build_gtest
  - cd build_gtest
  - cmake ../googletest/
  - make
  - sudo make install
  - cd ..
  - ./build_mahjong.sh --lib test
  - ./build_mahjong.sh --player user
  - ./build_mahjong.sh --game simple
  - export CXX="clang++-3.7"
  - ./build_mahjong.sh --lib test
  - ./build_mahjong.sh --player user
  - ./build_mahjong.sh --game simple

sudo: required

